model_list: 
  # with model: ollama_chat/* the options are correctly 
  # set (like keep_alive and num_ctx)

  # Groq
  - model_name: groq-llama3-8b-8192
    litellm_params:
      model: groq/llama3-8b-8192
      api_key: "os.environ/GROQ_API_KEY"

  # Llama Family (different types)
  - model_name: llama3.3
    litellm_params:
      model: ollama_chat/llama3.3:latest
      api_base: http://localhost:11434
      temperature: 0
      keep_alive: 24h
      num_ctx: 8192
      
  - model_name: llama3.1-8b
    litellm_params:
      model: ollama/llama3.1:8b
      api_base: http://localhost:11434
  
  # Qwen Family
  - model_name: qwen2.5-3b
    litellm_params:
      model: ollama_chat/qwen2.5:3b      
      api_base: http://localhost:11434
      temperature: 0
      keep_alive: 24h
      num_ctx: 8192
  - model_name: qwen2.5-7b
    litellm_params:
      model: ollama_chat/qwen2.5:7b
      api_base: http://localhost:11434
      temperature: 0
      keep_alive: 24h
      num_ctx: 8192
  - model_name: qwen2.5-14b  
    litellm_params:
      model: ollama_chat/qwen2.5:14b
      api_base: http://localhost:11434
      temperature: 0
      keep_alive: 24h
      num_ctx: 8192
  - model_name: qwen2.5-32b
    litellm_params:
      model: ollama_chat/qwen2.5:32b
      api_base: http://localhost:11434
      temperature: 0
      keep_alive: 24h
      num_ctx: 8192

  # Qwen-coder Family
  - model_name: qwen2.5-coder-3b
    litellm_params:
      model: ollama/qwen2.5-coder:3b
      api_base: http://localhost:11434
      temperature: 0
      keep_alive: 24h
      num_ctx: 8192
  - model_name: qwen2.5-coder-7b
    litellm_params:
      model: ollama_chat/qwen2.5-coder:7b
      api_base: http://localhost:11434
      temperature: 0
      keep_alive: 24h
      num_ctx: 8192
  - model_name: qwen2.5-coder-32b
    litellm_params:
      model: ollama_chat/qwen2.5-coder:32b
      api_base: http://localhost:11434
      temperature: 0
      keep_alive: 24h
      num_ctx: 12288

  # Granite IBM Family
  - model_name: granite-coder-20b
    litellm_params:
      model: ollama/qwen2.5-coder:3b
      api_base: http://localhost:11434
      temperature: 0
      keep_alive: 24h
      num_ctx: 8192
      

litellm_settings:
  host: "localhost"

