[project]
name = "orqa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bidict>=0.23.1",
    "bitarray>=3.8.0",
    "blend",
    "cryptography",
    "duckdb>=1.4.3",
    "fastapi>=0.135.2",
    "fastexcel>=0.19.0",
    "inflection>=0.5.1",
    "jsonlines>=4.0.0",
    "litellm>=1.80.10",
    "mcp>=1.2",
    "elasticsearch>=8,<9",
    "matplotlib>=3.10.8",
    "networkx>=3.6.1",
    "numpy>=1.26",
    "pandas>=2.3.3",
    "pip>=26.0.1",
    "polars>=1.36.1",
    "pyarrow>=22.0.0",
    "pyyaml>=6.0.3",
    "requests>=2.33.1",
    "scikit-learn>=1.4",
    "seaborn>=0.13.2",
    "shapely>=2.0",
    "tqdm>=4.67.1",
    "ulod",
    "uvicorn>=0.42.0",
    "valentine>=0.4.1",
    "wrapt-timeout-decorator>=1.5.1",
    "tabulate",
]

[tool.uv.sources]
ulod = { git = "https://github.com/nanni00/ULOD" }
blend = { git = "https://github.com/nanni00/Blend" }

[tool.ty.environment]
root = ["./src"]
